  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/API || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Calendar || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Command || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Configuration || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Controller || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/DataFixtures || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Doctrine || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Entity || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Event || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/EventSubscriber || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Export || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Invoice || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Model || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Repository || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Security || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Timesheet || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Twig || exit 1
  #/opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Utils || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Validator || exit 1
  /opt/kimai/vendor/bin/phpunit /opt/kimai/tests/Voter || exit 1