CREATE DATABASE kimai_ad_141;
CREATE DATABASE kimai_ad_141_x;
CREATE DATABASE kimai_ad_14;
CREATE DATABASE kimai_fd_14;
CREATE DATABASE kimai_fa_14;
CREATE DATABASE kimai_fd_141;
CREATE DATABASE kimai_fq_141;
