name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build fpm dev
      run: docker build . --file Dockerfile --tag kimai:fpm-dev
    
    - name: start mysql
      run: |
        docker run --rm -d --name kimai-mysql-testing \
          -e MYSQL_DATABASE=kimai \
          -e MYSQL_USER=kimai \
          -e MYSQL_PASSWORD=kimai \
          -e MYSQL_ROOT_PASSWORD=kimai \
          -p 3399:3306 -d mysql
          
    - name: run test container
      run: docker network create --driver bridge kimai-test
        
    - name: run test container
      run: docker run --rm --network kimai-test --name kimai-test-fpm-${KIMAI_VERSION}-prod -ti \
          -e DATABASE_URL=mysql://kimai:kimai@kimai-mysql-testing:3306/kimai \
          --entrypoint /self-test.sh \
          kimai/kimai2:kimai:fpm-dev

	
