name: 'Test'

on:
  workflow_dispatch:
    inputs:
      KIMAI:
        description: "Kimai version"
        required: true
        default: 1.16.9
  repository_dispatch:
    types: [kimai_release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo payload
        run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - name: Echo inputs
        run: |
          echo "KIMAI=${KIMAI}"
          echo "TIMEZONE=${TIMEZONE}"
      - name: Check for payload
        run: |
          if ! -z ${{ github.event.client_payload.KIMAI }}; then
            echo "kv=${{ github.event.client_payload.KIMAI }}" >> $GITHUB_ENV
            echo "kv set from payload"
          else
            echo "kv=${KIMAI}" >> $GITHUB_ENV
            echo "kv set from inputs"
